version: '3.8'

services:
  db:
    image: postgres:16-bullseye
    hostname: db
    restart: always
    env_file:
      - .db.env
    volumes:
      - ./local-db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - db

networks:
  db:
    driver: bridge
